
spring:
  application:
    name: lab-4-sentence
  config:
    import: "optional:configserver:http://localhost:8001"

# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://localhost:8010/eureka/

server:
  port: 8020